### ISSUE TITLE
Possible to render full breadcrumb path?

### ISSUE THREAD

**Issue by fipp** [Scrum/vue-2-breadcrumbs#105]
Hi, is it possible for `<Breadcrumbs />` to render the full breadcumb path, e.g. `Path 1 > Path 2 > Path 3 > Path 4`, and not just the current one and the parent?

**Comment by Scrum** [comment]
The full path is always displayed for example in [demo](https://scrum.github.io/vue-2-breadcrumbs/)
![Screenshot 2020-10-09 at 15 09 14](https://user-images.githubusercontent.com/2789192/95581335-7d85ba00-0a41-11eb-95d5-5d6b26a6b2a8.png)

**Comment by fipp** [comment]
Hmm strange. I'm getting the current page and the parent, not the grand-aprent when I'm on a grandchild page, with or without template. Using version `0.7.9`. Here's my router config, do you see anything bad off the bat?

```
{
    mode: 'history',
    routes: [
      {
        path: '/my-service',
        name: 'FrontPage',
        component: FrontPage,
        meta: {
          breadcrumb: 'Front page'
        }
      },
      {
        path: '/my-service/cars',
        name: 'Cars',
        component: Cars,
        meta: {
          breadcrumb: {
            label: 'Cars',
            parent: 'FrontPage'
          }
        }
      },
      {
        path: '/my-service/car/:carId',
        name: 'CarPage',
        component: CarPage,
        meta: {
          breadcrumb: {
            label: 'Car',
            parent: 'Cars'
          }
        }
      },
    ],
  }
```

So in this instance, when I'm on `/my-service/car/:carId`. I see two items in the breadcrumb, "Car" and "Car", would like to see "Front page" as well

**Comment by Scrum** [comment]
@fipp Hello

1. You are pointing the wrong way
```diff
      {
-        path: '/my-service/cars',
+        path: '/cars',
        name: 'Cars',
        component: Cars,
        meta: {
          breadcrumb: {
            label: 'Cars',
            parent: 'FrontPage'
          }
        }
      },
```

2. I think it is better to use children for dynamic paths

```js
{
  path: '/cars',
  name: 'Cars',
  component: Cars,
  meta: {
    breadcrumb: {
      label: 'Cars',
      parent: 'FrontPage'
    }
  },
  children: [
    {
      path: ':carId',
      name: 'CarPage',
      component: CarPage,
      meta: {
        breadcrumb: (params) => `${params.carId}`
      }
    }
  ]
}
```

3. I realized that there is an error in displaying the path if there are more than one parent

**Comment by Scrum** [comment]
@fipp after you submit paths and install version 0.7.10 your path will be complete

**Comment by fipp** [comment]
Thanks @Scrum, I got the full path with `0.7.10`. Kudos for a quick bug-fix! :)
