### ISSUE TITLE
It's possible to have an Async label ?

### ISSUE THREAD

**Issue by re2005** [Scrum/vue-2-breadcrumbs#107]
Hi, thanks for this awesome lib!

My question is how to use in async way.

Lets say, Breadcrumb is to a product page and I want to show the product name

**home -> category -> product name**

Something like this (ie)

```
meta: {
  async breadcrumb() {
  const { data } = await api.get('product');
  const name = data.name;
  return {
    label: name
  };
  }
}
```

How to do that, if possible ?

**Comment by Scrum** [comment]
@re2005 Hi, thanks for an interesting idea, but I'll try to figure out how to do it. If you have any ideas, feel free to submit them. PR are also welcomed

**Comment by re2005** [comment]
Can u accept a promise inside the component:

`const label = this.getBreadcrumb(crumb.meta.breadcrumb);`

**Comment by Scrum** [comment]
So far, I do not see opportunities to implement this for several reasons:

1. The router does not work with promises
2. Rendering doesn't work with promises

Either I have not completely figured out the ecosystem `vue` and `vue-router`

**Comment by re2005** [comment]
Thanks for the feedback. Maybe on Vue3 this is something that will work.

I've also tried but didn't succeed.

Keep u posted if any update on my side.

Thanks

**Comment by karladler** [comment]
I'm not that deep into vue, but maybe it's an idea to use a similar logic like the vue-meta plugin. So that a child component can export certain fields to overwrite template strings in the parents.
https://github.com/nuxt/vue-meta

**Comment by Scrum** [comment]
> I'm not that deep into vue, but maybe it's an idea to use a similar logic like the vue-meta plugin. So that a child component can export certain fields to overwrite template strings in the parents. https://github.com/nuxt/vue-meta

Thanks anyway, I'll look into this pack!
