### ISSUE TITLE
Parent property doesn't work

### ISSUE THREAD

**Issue by VladymyrKarpov** [Scrum/vue-2-breadcrumbs#109]
Hi, thanks for your work. I'm not able to work parents feature properly. As I understand when i navigate to route with parent it will find it but nothing happens. Could you please help and explain?
 children: [
                    {
                        path: '/',
                        component: ownCategories,
                        name: 'documents',
                        meta: {
                            breadcrumb: 'All'
                        },
                    },
                    {
                        path: 'filelist/:categoryId',
                        component: fileList,
                        name: 'fileList',
                        props: true,
                        meta: {
                            breadcrumb(){
                                const name = this.$route.params.name
                                return {label: name, parent: 'documents'}
                            }
                        }
                    },

**Comment by Scrum** [comment]
Hi, you can see how the documentation is organized, clone it and play around. Documentation sources are located [here](https://github.com/Scrum/vue-2-breadcrumbs/tree/master/src/docs), demo can be viewed [here](https://scrum.github.io/vue-2-breadcrumbs/). The source code for the demo routing is [here](https://github.com/Scrum/vue-2-breadcrumbs/blob/master/src/docs/src/router/index.ts).

If you fail, post an example on the github and let me know, I'll try to figure it out

**Comment by VladymyrKarpov** [comment]
Hi, thank for reply. This construction 
meta: {
      breadcrumb: {
        label: 'Parent to settings',
        parent: 'settings'
      }
    },
does nothing. Parent route doesn't appear as i expect. https://take.ms/nSVK2M you can check it in your demo https://scrum.github.io/vue-2-breadcrumbs/parent

**Comment by Scrum** [comment]
@VladymyrKarpov Thanks, good find
