### ISSUE TITLE
How can I use it with Nuxt?

### ISSUE THREAD

**Issue by apithy-isidro-martinez** [Scrum/vue-2-breadcrumbs#115]
Nuxt routes are dynamically generated, so I can't edit or shouldn't touch the router.js So how can I integrate it into Nuxt?

**Comment by Scrum** [comment]
> Nuxt routes are dynamically generated, so I can't edit or shouldn't touch the router.js So how can I integrate it into Nuxt?

This is a good question and an interesting feature. Now I am not ready to answer you, but I will investigate this issue.

**Comment by Scrum** [comment]
@apithy-isidro-martinez @jbclot now available in version v0.8.0

**Comment by apithy-isidro-martinez** [comment]
wow thank you for making it possible.
