### ISSUE TITLE
[docs]: Vue-router params

### ISSUE THREAD

**Issue by furyscript** [Scrum/vue-2-breadcrumbs#39]
Hi,

I'm actually using this plugin [link](https://github.com/samturrell/vue-breadcrumbs) for manage breadcrumbs on my site.
This not support the route params like `/post/:id` becasue vue block vue route by using `Object.freeze` as you can see on https://github.com/samturrell/vue-breadcrumbs/issues/1

Your project does it support vue route params in breadcrumbs?

**Comment by Scrum** [comment]
@furyscript Hi, yep see [demo](http://inside-demo.github.io/vue-demo/)

Please do not forget to put the star projects that you like))
