### ISSUE TITLE
[feat]: Pass additional params into breadcrumb function

### ISSUE THREAD

**Issue by gdereese** [Scrum/vue-2-breadcrumbs#40]
I like that you allow specifying a function for a route's breadcrumb so that the text can be dynamically generated.  

To expand on that idea, it would be great to have the current route parameters passed into the breadcrumb function so that the consumer could use those params as well.

For example, if I have a route `/customer/:id`, I'd like to be able to use the `id` route parameter to lookup the customer name so that I can display breadcrumbs like this:

**Home > Customers > John Doe**

I'd be happy to submit a pull request for this feature if you'd take it.

**Comment by Scrum** [comment]
@gdereese Hi

> I'd be happy to submit a pull request for this feature if you'd take it.

I will be happy with any contributions if this does not break the general ideology of the package.

**Comment by gdereese** [comment]
Done, see pull request #41.

**Comment by Scrum** [comment]
@gdereese  Thank you very much for your contribution, it is very important for the project. https://github.com/Scrum/vue-2-breadcrumbs/pull/42

Please do not forget to put the star projects that you like))
