### ISSUE TITLE
Make it independent of Bootstrap

### ISSUE THREAD

**Issue by andylima** [Scrum/vue-2-breadcrumbs#47]
It seems this is the most flexible (while staying easy-to-use) breadcrumb solution for Vue.js.

…But I don't  use Bootstrap — I use Bulma (which I really love) — So it would be great if the visual part could be completely customized.

Thank you!

**Comment by Scrum** [comment]
@andylima Hi, already scheduled in [mileston-0.4.0](https://github.com/Scrum/vue-2-breadcrumbs/issues/44)
