### ISSUE TITLE
[fix]: Error on IE 11

### ISSUE THREAD

**Issue by babak-f** [Scrum/vue-2-breadcrumbs#49]
My setup consists of webpack (with vue loader) and babel, for transpiling JavaScript into previous ES versions. 

In IE 11 I get the following error on the following line of the output JavaScript file. The error points at the 378th character in the line. 

> Expected ':'

```javascript 
Object.defineProperty(_exports,"__esModule",{value:!0}),_exports.default=void 0;var _default={install(Vue,options){Object.defineProperties(Vue.prototype,{$breadcrumbs:{get(){var _this=this,breadcrumbs=this.$route.matched.map(function(routeRecord){var path=routeRecord.path.length?routeRecord.path:"/",route=routeRecord;return Object.keys(_this.$route.params).forEach(function(param){path=route.path.replace(":"+param,_this.$route.params[param])},_this),route.path=path,route},this);return breadcrumbs}}});Vue.component("breadcrumbs",Object.assign({methods:{getBreadcrumb:function getBreadcrumb(bc){return"function"==typeof bc?bc(this.$route.params):bc}},template:`
```

As a result, the entire page fails to load. 

I assume that babel has taken care of transpiling the script to a version compatible with IE 11, so I guess it's the breadcrumb code itself that is causing the issue. Just a guess though ;)

Module version used: latest so far (0.4.0)

**Comment by Scrum** [comment]
@babak-f Hi, I see no reason to support outdated browsers. If you have a solution I will always consider it. Send your pull requests
