### ISSUE TITLE
[feat]: Query object

### ISSUE THREAD

**Issue by etorresys** [Scrum/vue-2-breadcrumbs#53]
How can i access to query object of $route? 

` meta: {
            authenticated: true,
            title: 'Test123',
            breadcrumb: (params) => { 
                 //Here i get only $route.params
            }
}`

**Comment by Scrum** [comment]
@etorresys Hi, thanks for your interest in the package. I implemented the call in context and now you can get all route property by `this.$route`.

see [example](https://github.com/Scrum/vue-2-breadcrumbs#example) for route `baz` or see [demo](http://inside-demo.github.io/vue-demo/#/baz)
