### ISSUE TITLE
[fix]: documentation clarification: named routes

### ISSUE THREAD

**Issue by difuoan** [Scrum/vue-2-breadcrumbs#55]
Just wanted to say that I spend multiple hours trying to figure out why the plugin was mixing up my route-params. Turns out because I used named routes, which seem to clash with the plugin for some reason.

This is not really documented, which would have been great for me, and very likely will be for others in the future.

**Comment by Scrum** [comment]
@difuoan Hi, thanks for feedback, can you set an example?

**Comment by kavayzin** [comment]
@difuoan, @Scrum We had a similar problem. Here is an example: http://jsfiddle.net/qbw0douh/1/.
Description of the problem:
after clicking on the link which contains the named parameter, all other links become invalid.
For example, after clicking on a link, the parameter "entityName" in which is equal to "entity1", this code is `<router-link: to = "{name: 'entities', params: {entityName: 'entity2'}}"> entities 2 < / router-link> `generates the following `<a href="/settings/entities/entity1" class="router-link-active"> entities 2 </a>` tag

**Comment by Scrum** [comment]
@kavayzin Hi, thanks for feedback, I will try to solve it soon.

**Comment by Scrum** [comment]
@kavayzin Hi, thanks for feedback, I will try to solve it soon.

**Comment by Scrum** [comment]
@difuoan @kavayzin Done, I regret the lack of time to solve this problem.
