### ISSUE TITLE
Change template inside component

### ISSUE THREAD

**Issue by dlishtvan** [Scrum/vue-2-breadcrumbs#56]
Hi. I want to change template inside my component. The problem is: method `getBreadcrumb(crumb.meta.breadcrumb)` is not defined on the instance. How I can fix  that?
example of my code: 

```
<template id="crumbs">
  <nav v-if="$breadcrumbs.length" class="breadcrumb" aria-label="breadcrumb">
    <ul class="breadcrumb">
      <li v-for="(crumb, key) in $breadcrumbs" v-if="crumb.meta.breadcrumb" :key="key" class="breadcrumb-item active" aria-current="page">
        <router-link :to="{ path: crumb.path }">{{ getBreadcrumb(crumb.meta.breadcrumb) }}</router-link>
      </li>
    </ul>
  </nav>
</template>
<script>
import Vue from 'vue';
import breadcrumbs from 'vue-2-breadcrumbs';

Vue.use(breadcrumbs, {
  template: '#crumbs'
});
```

**Comment by Scrum** [comment]
@letanure Hi, try
```js
Vue.use(breadcrumbs, {
  methods: {
    getBreadcrumbs() {...}
  },
  template: '#crumbs'
});
```

**Comment by dlishtvan** [comment]
> @letanure Hi, try
> 
> ```js
> Vue.use(breadcrumbs, {
>   methods: {
>     getBreadcrumbs() {...}
>   },
>   template: '#crumbs'
> });
> ```

unfortunately same error

**Comment by Scrum** [comment]
hmmm, may be 
```js
<script>
import Vue from 'vue';
import breadcrumbs from 'vue-2-breadcrumbs';

Vue.use(breadcrumbs, {
  template: '#crumbs'
});

export default {
  methods: {
    getBreadcrumbs() {...}
  }
}
</script>

**Comment by dlishtvan** [comment]
> hmmm, may be
> 
> ```js
> <script>
> import Vue from 'vue';
> import breadcrumbs from 'vue-2-breadcrumbs';
> 
> Vue.use(breadcrumbs, {
>   template: '#crumbs'
> });
> 
> export default {
>   methods: {
>     getBreadcrumbs() {...}
>   }
> }
> </script>
> ```

this is work, but how I can extend code of this method, for example I need something like this.

```
export default {
  methods: {
    getBreadcrumbs = breadcrumbs.getBreadcrumbs();
  }
}
```

and just use it on my template? Do you understand what I want?

**Comment by dlishtvan** [comment]
<img width="1035" alt="Снимок экрана 2019-04-25 в 13 00 00" src="https://user-images.githubusercontent.com/24511249/56727815-25c69680-675a-11e9-8e1a-53d60539393d.png">

**Comment by dlishtvan** [comment]
<img width="1035" alt="Снимок экрана 2019-04-25 в 13 01 54" src="https://user-images.githubusercontent.com/24511249/56727914-58708f00-675a-11e9-9638-79100ec4be21.png">

**Comment by Scrum** [comment]
> Do you understand what I want?

I'm not sure that I understand your idea, but it is probably worth making it as a component and reuse it.

**Comment by dlishtvan** [comment]
I made as  in a doc. 
```
Vue.use(VueBreadcrumbs, {
  template:
    `<nav class="breadcrumb" v-if="$breadcrumbs.length" aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li v-for="(crumb, key) in $breadcrumbs" v-if="crumb.meta.breadcrumb" :key="key" class="breadcrumb-item active" aria-current="page">
          <router-link :to="{ path: crumb.path }">{{ getBreadcrumb(crumb.meta.breadcrumb) }}</router-link>
        </li>
      </ol>
    </nav>`
});
```

**Comment by Scrum** [comment]
> Can I close issue?

Of course, if you find a solution
