### ISSUE TITLE
You are using the runtime-only build of Vue.

### ISSUE THREAD

**Issue by grasmachien** [Scrum/vue-2-breadcrumbs#64]
Hi,

I was trying out this plugin but never got it to work.
Is it still supposed to work with Vue 2.6.10 and Vue Router 3.0.7 ?

When I include the <breadcrumbs/> component I'm getting the following error.
"[Vue warn]: You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build."

I'm kind of assuming I really should not enable runtimeCompiler to get this to work.

**Comment by Scrum** [comment]
@grasmachien Hi, put an example on the githab so that I could see it. But I believe that you need to properly configure your collector. you can read more [here](https://vuejs.org/v2/guide/installation.html#Runtime-Compiler-vs-Runtime-only)

**Comment by grasmachien** [comment]
My project is just a clean, new project created with the Vue CLI.
I should not need to configure anything more than that.

**Comment by Scrum** [comment]
I created an [example](https://github.com/inside-demo/vue-cli-breadcrumbs) using Vue Cli, where everything works without errors. See on address `localhost:8080/#/foo/bar`

i'm used Runtime + Compiler

**Comment by grasmachien** [comment]
Nice.
But you made some changes when creating the Vue Cli project, right?
My package.json just looks like this.

{
  "name": "vue-test",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "core-js": "^2.6.5",
    "createjs-cmd": "^0.1.0",
    "gsap": "^2.1.3",
    "vue": "^2.6.10",
    "vue-2-breadcrumbs": "^0.5.1",
    "vue-router": "^3.0.7"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^3.9.0",
    "@vue/cli-plugin-eslint": "^3.9.0",
    "@vue/cli-service": "^3.9.0",
    "babel-eslint": "^10.0.1",
    "eslint": "^5.16.0",
    "eslint-plugin-vue": "^5.0.0",
    "vue-template-compiler": "^2.6.10"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/essential",
      "eslint:recommended"
    ],
    "rules": {},
    "parserOptions": {
      "parser": "babel-eslint"
    }
  },
  "postcss": {
    "plugins": {
      "autoprefixer": {}
    }
  },
  "browserslist": [
    "> 1%",
    "last 2 versions"
  ]
}

**Comment by Scrum** [comment]
no, there were no changes - used `vue-cli@2.9.6`

**Comment by grasmachien** [comment]
I see!
You are using a depricated version of the Vue Cli.
https://github.com/vuejs/vue-cli/tree/v2#vue-cli--
=> vue-cli is deprecated, see the new documentation.

I'm using Vue CLI v3.9.2

**Comment by Scrum** [comment]
currently only version `2.x` support

**Comment by Scrum** [comment]
transfer the template to declarative

**Comment by Scrum** [comment]
@grasmachien done
