### ISSUE TITLE
Works with vue HISTORY mode? 

### ISSUE THREAD

**Issue by davidreyg** [Scrum/vue-2-breadcrumbs#69]

**Comment by Scrum** [comment]
@davidreyg hi, not but good point

**Comment by Scrum** [comment]
@davidreyg Hi, exploring this question, I noticed that the plugin works with the history mode, but not all.  Could you describe what difficulties you encountered?

**Comment by Scrum** [comment]
@davidreyg work in my demo https://scrum.github.io/vue-2-breadcrumbs/
