### ISSUE TITLE
How do you actually insert the breadcrumbs on to the page?

### ISSUE THREAD

**Issue by dahousecat** [Scrum/vue-2-breadcrumbs#75]
The documentation doesn't say how to add them to a component.

The [`vue-2-crumbs`](https://www.npmjs.com/package/vue-2-crumbs) package makes `<app-breadcrumbs>` available - but I can't see anything equivalent in this package.

**Comment by Scrum** [comment]
@dahousecat Hi, thanks for noticing this flaw. I supplemented the documentation.

Uses a registered name `<Breadcrumbs>`
