### ISSUE TITLE
How to set route parent?

### ISSUE THREAD

**Issue by dahousecat** [Scrum/vue-2-breadcrumbs#76]
I can't see any way of defining what the routes parent should be.

Again to use an example from [`vue-2-crumbs`](https://www.npmjs.com/package/vue-2-crumbs) it allows:
```
meta: {
    breadcrumb: { parent: 'dashboard' }
}
```

Unfortunately that plugin doesn't appear to work with SSR was hoping this one would!

**Comment by Scrum** [comment]
@dahousecat Hi, great option, I will implement this soon

**Comment by Scrum** [comment]
@dahousecat Hi

> Unfortunately that plugin doesn't appear to work with SSR was hoping this one would!

I just checked it out and it worked out for me [demo](https://github.com/inside-demo/vue-2-breadcrumb-ssr-demo), could you tell me what problems you encountered ?

**Comment by maplerain1984** [comment]
how to set parent with query params?
