### ISSUE TITLE
options object template override seems not to be working

### ISSUE THREAD

**Issue by heyimmowee** [Scrum/vue-2-breadcrumbs#88]
First, thanks for your work, it works well with quasar and ssr.

I'm looking to override the default template (https://github.com/Scrum/vue-2-breadcrumbs#options) to use the breadcrumb quasar component but it does not affect the default one

**Comment by Scrum** [comment]
@heyimmowee Hi, I'm glad to know that someone needs this package.

Yes, thanks for your comment, you really need to determine what is included in the options and prioritize and choose one thing
