### ISSUE TITLE
Crumbs with multiple parents

### ISSUE THREAD

**Issue by rgbjay** [Scrum/vue-2-breadcrumbs#90]
Just wondering how I would go about showing crumbs with more than one parent, e.g

Home > Directory > Business Name

Thanks

**Comment by Scrum** [comment]
@rgbjay Hi, In my [example](https://scrum.github.io/vue-2-breadcrumbs/), there is an item in the menu `parent` which refers to `children` menu item `home` 
https://github.com/Scrum/vue-2-breadcrumbs/blob/c7c75562352e0993e0ce530040d07861537d3bd7/src/docs/src/router/index.ts#L8-L25
https://github.com/Scrum/vue-2-breadcrumbs/blob/c7c75562352e0993e0ce530040d07861537d3bd7/src/docs/src/router/index.ts#L110-L119

Perhaps you meant it? Let me know if I can help with anything else

**Comment by rgbjay** [comment]
Thanks this seems to do the trick!

**Comment by Scrum** [comment]
@rgbjay Always welcome, put stars if you like this project :)
