### ISSUE TITLE
Only create li element if breadcrumb returns a value

### ISSUE THREAD

**Issue by garethbradley** [Scrum/vue-2-breadcrumbs#91]
Hey,

I am writing a CRUD type app that has an Index, Show, New etc. pages. An excerpt from the routes looks like this:

```
{
                    component: LayoutPage,
                    path: '/services',
                    meta: {
                        breadcrumb() {
                            return (this.$route.name === 'services') ? '' : 'Services';
                        }
                    },
                    children: [
                        {
                            component: ServicesIndex,
                            name: 'services',
                            path: '/',
                            meta: {
                                breadcrumb: 'Services'
                            },
                        }, {
                            component: ServicesNew,
                            name: 'services-new',
                            path: 'new',
                            meta: {
                                breadcrumb: 'New'
                            }
                        }
```

If I don't put that logic into breadcrumb function of the /services parent, it will always show the breadcrumb li as a link (presumably because it matches the. 'services' route.

But now it creates the Breadcrumb **Home / / Services**. (Home is defined further up the routes)

Can the library be updated to exclude blank breadcrumb functions?

Cheers!

**Comment by Scrum** [comment]
@garethbradley Hi, thank you for your #92 , I would like to clarify a few points.

Do you have the opportunity to form a route as follows? it could solve your problem

> Note. Pay attention to the `path` in `children`

https://github.com/Scrum/vue-2-breadcrumbs/blob/c7c75562352e0993e0ce530040d07861537d3bd7/src/docs/src/router/index.ts#L52-L62
