### ISSUE TITLE
Q: Is it possible to change the label of a breadcrumb after page is rendered?

### ISSUE THREAD

**Issue by francisjyap** [Scrum/vue-2-breadcrumbs#99]
Here is the scenario:

User clicks on a link to Page B
Page B is a parent of Page A

So the breadcrumb will look like this:
Page A > Page B

But Page B is a page representing a specific resource, so it should be like so:
Page A > Resource Name

The resource name is retrieved via API. I have tried modifying the label via $breadcrumbs and calling $forceUpdate to no avail.

**Comment by Scrum** [comment]
@francisjyap Hi, you can try dynamic label name generation.

```js
,
    {
      path: '/params',
      name: 'Params',
      component: { template: '<h2>Params</h2>' },
      meta: {
        breadcrumb: routeParams => `route params id: ${routeParams.id}`
      }
    },
    {
      path: '/context',
      name: 'Context',
      component: { template: '<h2>Context</h2>' },
      meta: {
        breadcrumb() {
            const { name } = this.$route;
            return `name "${name}" of context route`;
        }
      }
    },
```

Let me know if there's anything else I can help you with

**Comment by NoorulainKhaliq** [comment]
had a similar question, is it possible to dynamically set the label?
```       
           breadcrumb: {
                label:  () => this.$route.params.name,
                parent: 'Items'
           }

**Comment by Scrum** [comment]
Do not hesitate to rediscover this task if I can still be useful to you.

```js
{
      path: '/context',
      name: 'Context',
      component: { template: '<h2>Context</h2>' },
      meta: {
        breadcrumb() {
            const { name } = this.$route;
            return {
              label: name,
              parent: 'Items'
            };
        }
      }
    }
```

**Comment by francesco-filicetti** [comment]
Hi, how to pass param to breadcrumbs if API is called after page components are rendered?
How to use dynamic label generation in this case?
Thank you

**Comment by Scrum** [comment]
> Hi, how to pass param to breadcrumbs if API is called after page components are rendered?
> How to use dynamic label generation in this case?
> Thank you

Hi, please provide a minimal example so that I can understand your question better.

**Comment by francesco-filicetti** [comment]
This is a single router item.
Label is actually formatted with che ```collection_id``` param. I would to pass a ```collection_name``` but I haven't it in my route path. My component retrieve it after an API call, using the id value. So, how can I pass it to breadcrumb after having API response?

```
{
path: 'media-collections/:collection_id/edit',
name: 'MediaCollectionEdit',
component: MediaCollectionEdit,
  meta: {
    breadcrumb() {
      return {
        label: this.$route.params.collection_id.toString(),
        parent: 'MediaCollections'
      }
    }
  },
}
```

**Comment by Scrum** [comment]
The documentation has an example of getting parameters as an argument to a method
```js
{
      path: '/params',
      name: 'Params',
      component: { template: '<h2>Params</h2>' },
      meta: {
        breadcrumb: routeParams => `route params id: ${routeParams.id}`
      }
    },
```

**Comment by francesco-filicetti** [comment]
thank you, but this not solves my problem.
In ```routeParams``` I haven't ```collection_name``` but only ```collection_id```

**Comment by Scrum** [comment]
> thank you, but this not solves my problem.
> In `routeParams` I haven't `collection_name` but only `collection_id`

https://github.com/Scrum/vue-2-breadcrumbs/blob/0509a92257a1c25e13229a5d93868c715a622977/src/index.ts#L34

**Comment by francesco-filicetti** [comment]
thank you.
I need to use this code in component or in router definition?

**Comment by francesco-filicetti** [comment]
I've tried to manually set ```this.$route.params.collection_name = "custom name"``` in my component, and it works if called beforeMounted(). But not if I pass an axios response value, because it's setted after breadcrumb is rendered...
so sorry, maybe you have already given me a solution but I can't make it work :(

**Comment by Scrum** [comment]
> I've tried to manually set `this.$route.params.collection_name = "custom name"` in my component, and it works if called beforeMounted(). But not if I pass an axios response value, because it's set after breadcrumb is rendered...
> so sorry, maybe you have already given me a solution but I can't make it work :(

The asynchronous option will most likely not be available, [see the comments](https://github.com/Scrum/vue-2-breadcrumbs/issues/107#issuecomment-764419734). I am still at the stage of solving this problem.

**Comment by francesco-filicetti** [comment]
thank you.
Is there any method to force breadcrumb refresh in component?
In the attachment you can see my actual situation... a numeric id in breadcrumb, the only parameter in route.params when page is created, before API call

![Selezione_327](https://user-images.githubusercontent.com/28479069/110784564-20996480-826a-11eb-9c68-effa98aba379.png)

**Comment by francesco-filicetti** [comment]
I've read the comments... is my use case :(
Thank you very much for your patience and for your time

**Comment by Scrum** [comment]
> I've read the comments... is my use case :(
> Thank you very much for your patience and for your time

Cheer up, I'll keep you posted 👍
